version: '3.8'

services:
  app:
    build: .
    image: my-task-manager-api:prod
    container_name: task-manager-prod
    ports:
      - "80:8080"
    env_file:
      - .env
    restart: unless-stopped
